name: build

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64_x86
    steps:
      - name: set git options
        run: |
          git config --global core.autocrlf false
          git config core.autocrlf
      - name: Get version
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: checkout implementation
        uses: actions/checkout@v2
        with:
          repository: actlaboratory/hiss
          ref: ${{ steps.tagName.outputs.tag }}
          token: ${{ secrets.access_token }}
          submodules: 'recursive'
      - name: prepare msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x86"
      - name: install python libraries
        run: |
          pip install scons markdown pyinstaller
          pip install -r sapiExtension/requirements.txt
      - name: Delete Unwanted Link to Stop It From Interfering
        run: rm /usr/bin/link.exe
        shell: bash
      - name: run unit tests
        run: |
          cd tests
          make
        env:
          ARCH_NAME: _${{ matrix.arch }}
      - name: run full build
        run: |
          make
        env:
          ARCH_NAME: _${{ matrix.arch }}
      - name: generate version info JSON
        run: |
          make version_info
      - name: publish automatic release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/nvda/HISS-${{ steps.tagName.outputs.tag }}.zip, build/nvda/HISS-${{ steps.tagName.outputs.tag }}.nvda-addon, HISS-${{ steps.tagName.outputs.tag }}_info.json,build/sapiExtension/dist/sapiExtension.zip
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
